// Comprehensive Live Demo dataset for client-side Vercel & offline demonstration

export interface MockCase {
  case_id: number;
  case_name: string;
  investigator: string;
  created_at: string;
  status: string;
  description: string;
  evidence_count: number;
  findings_count: number;
  risk_level: string;
  risk_score: number;
  evidence_list: any[];
  findings: any[];
  cia_scores: any[];
}

export const MOCK_CASES: MockCase[] = [
  {
    case_id: 1,
    case_name: "Ransomware Incident - Finance Server",
    investigator: "John Doe (Lead Examiner)",
    created_at: "2026-09-30 08:30:00",
    status: "OPEN",
    description: "Digital forensic investigation into unauthorized SSH intrusion, reconnaissance port scans, and malicious PowerShell execution targeting database backup storage.",
    evidence_count: 8,
    findings_count: 14,
    risk_level: "HIGH",
    risk_score: 8.5,
    evidence_list: [
      {
        evidence_id: 1,
        case_id: 1,
        filename: "auth_logs.csv",
        file_path: "evidence/auth_logs.csv",
        sha256_hash: "8f4e2c1a9d0b5e3f7a6c8e1b2d4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f",
        md5_hash: "4af16ff22dda676b1d517e96a132a78c",
        file_size_bytes: 49152,
        evidence_type: "log",
        source: "Linux Auth Syslog (/var/log/auth.log)",
        custody_officer: "John Doe",
        acquired_at: "2026-09-30 08:45:00",
        notes: "Contains 12 sequential authentication failures followed by accepted session from external IP.",
      },
      {
        evidence_id: 2,
        case_id: 1,
        filename: "sample_capture.pcap",
        file_path: "evidence/sample_capture.pcap",
        sha256_hash: "3a7b1c9e2d4f6a8b0c2e4f6a8b0c2e4f6a8b0c2e4f6a8b0c2e4f6a8b0c2e4f6a",
        md5_hash: "e99a18c428cb38d5f260853678922e03",
        file_size_bytes: 2621440,
        evidence_type: "pcap",
        source: "Network Gateway Interface (eth0)",
        custody_officer: "John Doe",
        acquired_at: "2026-09-30 09:15:00",
        notes: "Full packet capture covering attack timeframe. Shows TCP SYN scans and outbound exfiltration.",
      },
      {
        evidence_id: 3,
        case_id: 1,
        filename: "users.csv",
        file_path: "evidence/users.csv",
        sha256_hash: "b41d2fb74c5d57634fcf2c7c647611781f68a9e51293549ade561a9ff2a30cd3",
        md5_hash: "44d88612fea8a8f36de82e1278abb02f",
        file_size_bytes: 14320,
        evidence_type: "data",
        source: "Active Directory Export Baseline",
        custody_officer: "John Doe",
        acquired_at: "2026-09-30 09:30:00",
        notes: "Cryptographic baseline snapshot of administrative user accounts before incident.",
      },
      {
        evidence_id: 4,
        case_id: 1,
        filename: "users_tampered.csv",
        file_path: "evidence/users_tampered.csv",
        sha256_hash: "7c6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e",
        md5_hash: "275a021bbfb6487f7a1f2c3a5e6d7b8c",
        file_size_bytes: 15110,
        evidence_type: "data",
        source: "Compromised Host Filesystem",
        custody_officer: "John Doe",
        acquired_at: "2026-09-30 09:45:00",
        notes: "Recovered post-incident file. Hash mismatch indicates unauthorized modification.",
      },
      {
        evidence_id: 5,
        case_id: 1,
        filename: "test_malware_sample.bin",
        file_path: "evidence/test_malware_sample.bin",
        sha256_hash: "131f95c51cc819465fa1797f6ccacf9d494aaaff46fa3eac73ae63ffbcf16fdb",
        md5_hash: "a3d2e5f8c1b2d4e6f8a9b0c1d2e3f4a5",
        file_size_bytes: 84920,
        evidence_type: "malware",
        source: "Temp Directory Artifact (/tmp/.sys_daemon)",
        custody_officer: "John Doe",
        acquired_at: "2026-09-30 10:00:00",
        notes: "Suspicious binary identified via anomalous high entropy and matching known signature database.",
      },
      {
        evidence_id: 6,
        case_id: 1,
        filename: "incident_briefing.pdf",
        file_path: "evidence/incident_briefing.pdf",
        sha256_hash: "5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c",
        md5_hash: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d",
        file_size_bytes: 182400,
        evidence_type: "document",
        source: "User Desktop Evidence",
        custody_officer: "John Doe",
        acquired_at: "2026-09-30 10:30:00",
        notes: "Forensic PDF analyzed for embedded metadata, creation author, and software timestamps.",
      },
      {
        evidence_id: 7,
        case_id: 1,
        filename: "file_events.csv",
        file_path: "evidence/file_events.csv",
        sha256_hash: "9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a",
        md5_hash: "6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b",
        file_size_bytes: 38912,
        evidence_type: "event_log",
        source: "Auditd Filesystem Journal",
        custody_officer: "John Doe",
        acquired_at: "2026-09-30 11:00:00",
        notes: "Recorded 23 file unlinks and deletions within a 4-minute anti-forensic burst window.",
      },
      {
        evidence_id: 8,
        case_id: 1,
        filename: "suspicious_script.ps1",
        file_path: "evidence/suspicious_script.ps1",
        sha256_hash: "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
        md5_hash: "f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6",
        file_size_bytes: 5210,
        evidence_type: "script",
        source: "Scheduled Tasks Directory",
        custody_officer: "John Doe",
        acquired_at: "2026-09-30 11:30:00",
        notes: "PowerShell payload containing base64 obfuscation and encoded download cradles.",
      },
    ],
    findings: [
      {
        finding_id: 1,
        technique: "Log Forensics",
        finding: "Brute-force attack detected: 12 failed authentication attempts within 60s from 192.168.1.20 targeting accounts admin, root, svc_backup.",
        severity: "CRITICAL",
        confidence: 9.5,
        created_at: "2026-09-30 08:48:12",
      },
      {
        finding_id: 2,
        technique: "Log Forensics",
        finding: "Anomalous off-hours access: Successful login for account svc_admin at 02:45:18 AM from untrusted public IP 198.51.100.45.",
        severity: "HIGH",
        confidence: 9.0,
        created_at: "2026-09-30 08:49:05",
      },
      {
        finding_id: 3,
        technique: "Network Forensics",
        finding: "Reconnaissance TCP SYN port scan detected originating from 10.0.0.15 across ports 21, 22, 80, 443, 8080 (32 distinct destination ports).",
        severity: "HIGH",
        confidence: 9.2,
        created_at: "2026-09-30 09:20:44",
      },
      {
        finding_id: 4,
        technique: "Network Forensics",
        finding: "Data exfiltration detected: Large outbound data transfer of 14,892,100 bytes transmitted over port 443 to external IP 203.0.113.88.",
        severity: "CRITICAL",
        confidence: 9.4,
        created_at: "2026-09-30 09:22:15",
      },
      {
        finding_id: 5,
        technique: "Network Forensics",
        finding: "Suspicious DNS tunneling / C2 heartbeat queries observed for domain 'c2-listener.darknet-routing.xyz'.",
        severity: "HIGH",
        confidence: 8.8,
        created_at: "2026-09-30 09:23:01",
      },
      {
        finding_id: 6,
        technique: "File Integrity Analysis",
        finding: "Cryptographic baseline integrity failure: users_tampered.csv hash mismatch compared to custody baseline users.csv (SHA-256 differs).",
        severity: "CRITICAL",
        confidence: 10.0,
        created_at: "2026-09-30 09:50:18",
      },
      {
        finding_id: 7,
        technique: "Malware Signature Analysis",
        finding: "Known malware hash match: test_malware_sample.bin matches educational Trojan signature in known threat repository (SHA-256: 131f95c...).",
        severity: "HIGH",
        confidence: 9.8,
        created_at: "2026-09-30 10:05:33",
      },
      {
        finding_id: 8,
        technique: "Malware Signature Analysis",
        finding: "High Shannon entropy detected: entropy value 7.84 > 7.0 indicative of packed executable or encrypted ransomware payload.",
        severity: "HIGH",
        confidence: 8.6,
        created_at: "2026-09-30 10:06:50",
      },
      {
        finding_id: 9,
        technique: "Malware Signature Analysis",
        finding: "YARA rule match triggered: rule 'CyberTrace_Suspicious_PowerShell' matched 3 obfuscation patterns in suspicious_script.ps1.",
        severity: "HIGH",
        confidence: 9.1,
        created_at: "2026-09-30 10:08:12",
      },
      {
        finding_id: 10,
        technique: "Metadata Forensics",
        finding: "Metadata discrepancy detected: Modification timestamp precedes creation timestamp on incident_briefing.pdf (potential timestomping).",
        severity: "MEDIUM",
        confidence: 8.0,
        created_at: "2026-09-30 10:35:10",
      },
      {
        finding_id: 11,
        technique: "Deleted-File Analysis",
        finding: "Anti-forensic mass deletion detected: 23 files deleted within 4 minutes; secure wipe tool marker 'sdelete' identified in event logs.",
        severity: "HIGH",
        confidence: 9.0,
        created_at: "2026-09-30 11:05:44",
      },
    ],
    cia_scores: [
      { technique: "Log Forensics", confidentiality: 8, integrity: 8, availability: 7, justification: "Detects unauthorized access and event timelines" },
      { technique: "Network Forensics", confidentiality: 9, integrity: 7, availability: 9, justification: "Identifies data transfer, scans, and disruption" },
      { technique: "File Integrity Analysis", confidentiality: 5, integrity: 10, availability: 7, justification: "Proves whether files were modified" },
      { technique: "Malware Signature Analysis", confidentiality: 8, integrity: 8, availability: 8, justification: "Detects malicious files and persistence indicators" },
      { technique: "Metadata Forensics", confidentiality: 6, integrity: 7, availability: 5, justification: "Provides file context and timeline clues" },
      { technique: "Deleted-File Analysis", confidentiality: 7, integrity: 9, availability: 6, justification: "Identifies evidence destruction and data loss" },
    ],
  },
  {
    case_id: 2,
    case_name: "Insider Threat - Intellectual Property Exfiltration",
    investigator: "John Doe (Lead Examiner)",
    created_at: "2026-09-28 14:15:00",
    status: "INVESTIGATING",
    description: "Investigation into proprietary source code repository exfiltration via encrypted archive staging and off-hours SFTP transfer.",
    evidence_count: 5,
    findings_count: 9,
    risk_level: "CRITICAL",
    risk_score: 9.2,
    evidence_list: [],
    findings: [],
    cia_scores: [
      { technique: "Log Forensics", confidentiality: 9, integrity: 7, availability: 6, justification: "Tracks privileged account abuse and off-hours sessions" },
      { technique: "Network Forensics", confidentiality: 10, integrity: 8, availability: 7, justification: "Traces large volume outbound encrypted file transfers" },
      { technique: "File Integrity Analysis", confidentiality: 7, integrity: 9, availability: 6, justification: "Confirms hash alteration on archive manifests" },
      { technique: "Malware Signature Analysis", confidentiality: 6, integrity: 7, availability: 6, justification: "Screens for staging tools and exfiltration scripts" },
      { technique: "Metadata Forensics", confidentiality: 8, integrity: 8, availability: 6, justification: "Reveals author identity and revision histories in archives" },
      { technique: "Deleted-File Analysis", confidentiality: 8, integrity: 9, availability: 7, justification: "Reconstructs unlinked staging directories" },
    ],
  },
  {
    case_id: 3,
    case_name: "APT Persistence & Anti-Forensics Activity",
    investigator: "John Doe (Lead Examiner)",
    created_at: "2026-09-25 11:00:00",
    status: "REVIEW",
    description: "Post-incident audit of system service injection, scheduled task persistence, and Windows event log wiping.",
    evidence_count: 6,
    findings_count: 11,
    risk_level: "MEDIUM",
    risk_score: 6.8,
    evidence_list: [],
    findings: [],
    cia_scores: [
      { technique: "Log Forensics", confidentiality: 7, integrity: 9, availability: 8, justification: "Identifies log clearing event IDs (Event 1102)" },
      { technique: "Network Forensics", confidentiality: 8, integrity: 7, availability: 8, justification: "Monitors beaconing intervals and DNS requests" },
      { technique: "File Integrity Analysis", confidentiality: 6, integrity: 10, availability: 7, justification: "Detects patched DLL files and registry entries" },
      { technique: "Malware Signature Analysis", confidentiality: 9, integrity: 9, availability: 8, justification: "Flags in-memory reflective loaders" },
      { technique: "Metadata Forensics", confidentiality: 6, integrity: 8, availability: 5, justification: "Identifies timestomped system binaries" },
      { technique: "Deleted-File Analysis", confidentiality: 8, integrity: 10, availability: 7, justification: "Traces shadow copy deletions (vssadmin delete)" },
    ],
  },
];
